### ISSUE TITLE
Migrate from PB12.6 to PB2017 - Issue with PBNISMTP

### ISSUE THREAD

**Issue by DennisDLittle** [bruce-armstrong/pbnismtp_sample#1]
Hi Bruce,

We recently upgraded to PB2017 from PB12.6.  We are having issues with pbnismtp.
I created a new library and imported the pbnismtp126.pbx file and compiled a pbd.  I added the new pbd and the pbx file to the working directory of the application.
Works in IDE, not in EXE.  We also added the crucial PB17 dlls to the start folder.

We get a bad runtime reference error when it gets to this line: l_smtp.SetRecipientEmail(ls_ToMail)
I am running the EXE on a different machine-it mimics the PRODUCTION runtime environment.

We’re running on a 32 bit platform.

It worked great in PB12.6, we're probably missing a dll or two for PB17, any ideas?

BTW - We tried the Dependency Walker- didn’t seem to help.  

Thanks

Dennis

**Comment by bruce-armstrong** [comment]
I can think of a couple of possible issues:

1.  A PBNI extension is compiled with an imported library from a particular version of PowerBuilder.  Chances are if you migrated the 12.6 version to 2017 the extension would still try to access the 12.6 PowerBuilder runtime DLLs.

2.  There were some recent changed to the PBNI extension (adding and removing method names) that this sample code wasn't in sync with.  I've since updated the sample.

I've modified the extension project so that it now generates extensions for both 12.6 and 2017. I've also updated the sample code here with workspaces for each version.  Finally, I created a release that contains the PBLs and PBXs for both that are current.  Please try them out.

**Comment by DennisDLittle** [comment]
Thanks Bruce.  I downloaded the pbnismtp_sample-master file.  I don’t see a pbx file.  Previously I just created a pbl and imported the pbx file.  How do I implement this?

**Comment by bruce-armstrong** [comment]
Go to the Releases page and download the pbnismtp_sample.zip file there.

https://github.com/bruce-armstrong/pbnismtp_sample/releases

**Comment by DennisDLittle** [comment]
Thanks Bruce.

**Comment by DennisDLittle** [comment]
Bruce,

Sorry to keep bothering you, but I can’t get this thing working.

1-Downloaded the latest pbnismtp126.pbx file
2-Created a new library: pbnismtp126.pbl
3-Imported PB extension: pbnismtp126.pbx
4-Built a PBD: pbnismtp126.pbd
5-Deleted pbnismtp126.pbl
6-Added pbnismtp126.pbd to the library list

32 bit.

It works great when I run on my local PB machine in IDE.

It bombs at the red line when running on the production machine.  We copy all the PBDs (including pbnismtp126.pbd and pbnismtp126.pbx) out to a ‘run’ folder and have a ‘start in’ folder for the DLLs.  I have to be missing a DLL somewhere.  We’ve tried dependency walker and the PB runtime packager, to no avail.

CODE SNIPPET
n_cpp_smtp l_smtp
TRY
     l_smtp = CREATE n_cpp_smtp
     if ls_ToMail <> '' then
          l_smtp.SetRecipientEmail(ls_ToMail)
     end if
     if ls_CcMail <> '' then
          l_smtp.SetCCRecipientEmail(ls_CcMail)
     end if

DLL list
[cid:image001.png@01D34283.CD0FF380]

Thanks,
Dennis

**Comment by bruce-armstrong** [comment]
Try process monitor.  https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

I believe this is causing the issue:

>>We copy all the PBDs (including pbnismtp126.pbd and pbnismtp126.pbx) out to a ‘run’ folder 
>>and have a ‘start in’ folder for the DLLs.

Unless that "run" folder is in the system or app path I imagine that the application can't find the PBX file.

**Comment by DennisDLittle** [comment]
Thanks Bruce.

**Comment by rajesh-1** [comment]
Hi Bruce, 

I downloaded the pbnismtp2017 sample and created a 64 bit exe in PB2017. It fails with an error "Bad runtime function reference at line 23 in clicked event of object cb_smtp of w_main." (Line 23: l_smtp.SetRecipientEmail ( ls_recipient  )) 

But, it works fine from 32 bit exe and PB 2017 IDE. I have pbnismtp2017.pbx file in the same folder where the exe is.

Any idea what could be the problem. Thanks.

**Comment by bruce-armstrong** [comment]
PBX files are basically custom C++ DLLs, which means they have a bitness.  The ones provided in the release on the pbnismtp project are 32 bit.  You'd need to grab the source and and a 64 bit compile to use it with a 64 bit PB application.
